"""A real OpenSSH server for the end-to-end tests.

Mocking an SSH server proves very little: the interesting failures are in the
handshake, in host key handling and in what sshd does with the permissions of
authorized_keys. So the tests run against sshd itself when the machine has
one, and skip when it does not.

The host key is generated by this package rather than by ssh-keygen, which
incidentally proves the generated format is one OpenSSH accepts.

Password logins can only be tested where sshd runs as root (it has to switch
to the target user). Where that is not possible, those tests skip.
"""

from __future__ import annotations

import getpass
import os
import shutil
import signal
import socket
import subprocess
import tempfile
import time
from dataclasses import dataclass
from typing import Optional

SSHD_CANDIDATES = ("/usr/sbin/sshd", "/usr/local/sbin/sshd", "/sbin/sshd")
SFTP_CANDIDATES = (
    "/usr/lib/openssh/sftp-server",
    "/usr/libexec/openssh/sftp-server",
    "/usr/libexec/sftp-server",
    "/usr/lib/ssh/sftp-server",
)
PASSWORD_USER = "hermesssh"
PASSWORD = "Pa$$ 'wörd\" \\ ;"


def find_sshd() -> Optional[str]:
    if os.name == "nt":
        return None
    return next((c for c in SSHD_CANDIDATES if os.path.exists(c)), None)


def _free_port() -> int:
    with socket.socket() as s:
        s.bind(("127.0.0.1", 0))
        return s.getsockname()[1]


def _wait_for_port(port: int, timeout: float = 10.0) -> bool:
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        try:
            with socket.create_connection(("127.0.0.1", port), timeout=0.5):
                return True
        except OSError:
            time.sleep(0.1)
    return False


def _ensure_password_user() -> bool:
    """Create a throwaway local account with a known password (root only)."""
    if os.geteuid() != 0 or shutil.which("useradd") is None:
        return False
    try:
        subprocess.run(["id", PASSWORD_USER], check=True, capture_output=True)
    except subprocess.CalledProcessError:
        subprocess.run(["useradd", "-m", "-s", "/bin/sh", PASSWORD_USER], check=True, capture_output=True)
    subprocess.run(["chpasswd"], input=f"{PASSWORD_USER}:{PASSWORD}".encode(), check=True, capture_output=True)
    home = os.path.expanduser(f"~{PASSWORD_USER}")
    # Start every run without keys, so the bootstrap is exercised for real.
    shutil.rmtree(os.path.join(home, ".ssh"), ignore_errors=True)
    return True


@dataclass
class TestServer:
    port: int
    user: str
    dir: str
    client_key_path: str
    authorized_keys_path: str
    password_user: Optional[str]
    process: subprocess.Popen

    def stop(self) -> None:
        try:
            self.process.send_signal(signal.SIGKILL)
            self.process.wait(timeout=5)
        except Exception:
            pass
        shutil.rmtree(self.dir, ignore_errors=True)

    def kill_connections(self) -> None:
        """End every per-connection sshd process, like a dropped network path would.

        The whole tree, not just the listener's children: each connection is a
        monitor ("sshd: user [priv]") with a child that holds the socket. Killed
        alone, the monitor leaves that child orphaned and the connection alive.
        That happens when sshd runs without root, as on CI runners and macOS.
        """
        descendants, frontier = [], [str(self.process.pid)]
        while frontier:
            found = subprocess.run(["pgrep", "-P", ",".join(frontier)], capture_output=True, text=True).stdout.split()
            descendants += found
            frontier = found
        if descendants:
            subprocess.run(["kill", "-KILL", *descendants], capture_output=True)


def start_test_server(generate_key_pair) -> Optional[TestServer]:
    sshd = find_sshd()
    if not sshd:
        return None
    sftp = next((c for c in SFTP_CANDIDATES if os.path.exists(c)), None)
    directory = tempfile.mkdtemp(prefix="hermes-ssh-sshd-")
    os.chmod(directory, 0o755)

    host_key = generate_key_pair("test host")
    host_key_path = os.path.join(directory, "host_ed25519")
    with open(host_key_path, "w") as handle:
        handle.write(host_key.private_key)
    os.chmod(host_key_path, 0o600)

    client_key = generate_key_pair("test client")
    client_key_path = os.path.join(directory, "client_ed25519")
    with open(client_key_path, "w") as handle:
        handle.write(client_key.private_key)
    os.chmod(client_key_path, 0o600)

    authorized = os.path.join(directory, "authorized_keys")
    with open(authorized, "w") as handle:
        handle.write(client_key.public_key + "\n")
    os.chmod(authorized, 0o644)

    password_user = PASSWORD_USER if _ensure_password_user() else None
    port = _free_port()
    config_path = os.path.join(directory, "sshd_config")
    lines = [
        f"Port {port}",
        "ListenAddress 127.0.0.1",
        f"HostKey {host_key_path}",
        f"PidFile {os.path.join(directory, 'sshd.pid')}",
        # The test user's key sits in the temp dir; everyone else uses their own home.
        f"AuthorizedKeysFile {authorized} .ssh/authorized_keys",
        "StrictModes no",
        "UsePAM no",
        f"PasswordAuthentication {'yes' if password_user else 'no'}",
        "PubkeyAuthentication yes",
        "AllowTcpForwarding yes",
        "GatewayPorts no",
        "ClientAliveInterval 0",
    ]
    if sftp:
        lines.append(f"Subsystem sftp {sftp}")
    with open(config_path, "w") as handle:
        handle.write("\n".join(lines) + "\n")

    if os.path.exists("/run") and os.geteuid() == 0:
        os.makedirs("/run/sshd", exist_ok=True)  # privilege separation directory

    process = subprocess.Popen([sshd, "-D", "-f", config_path, "-e"],
                               stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    if not _wait_for_port(port):
        process.kill()
        shutil.rmtree(directory, ignore_errors=True)
        return None
    return TestServer(port=port, user=getpass.getuser(), dir=directory, client_key_path=client_key_path,
                      authorized_keys_path=authorized, password_user=password_user, process=process)
